#!/bin/bash
# Behavioral health microservices.
alias bh-reporting='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-reporting-scripts/'
alias bh-analytics='code $HOME/AppDevelopment/DarioHealth/code/backend/analytics-ingest-events'
alias bh-auth0='code $HOME/AppDevelopment/DarioHealth/code/backend/auth0-customizations'
alias bh-assess='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-assess-app'
alias bh-auth0-to-logdna='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-auth0-to-logdna'
alias bh-coach='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-coach-suggestion-api'
alias bh-content='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-content-service'
alias bh-feature='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-feature-service'
alias bh-graphql='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-graphql-service'
alias bh-edge='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-lambda-edge'
alias bh-marketing='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-marketing-api'
alias bh-notification='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-notification-service'
alias bh-partner='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-partner-service'
alias bh-request='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-request-management'
alias bh-user='code $HOME/AppDevelopment/DarioHealth/code/backend/serverless-user-service'
alias bh-cloud='code $HOME/AppDevelopment/DarioHealth/code/backend/bh-cloudwatch-logs-to-logdna'

alias bh-react='code $HOME/AppDevelopment/DarioHealth/code/react-wayforward-app'
alias bh-lambda='code $HOME/AppDevelopment/DarioHealth/code/node-lambda-logger'
alias bh-meteor='code $HOME/AppDevelopment/DarioHealth/code/meteor-wayforward-app'

alias gh-create='echo "Add title :" && read title && echo "Add body : " && read body && gh pr create -t $title -b $body --label="in progress"'
alias gh-review='gh pr edit --add-label="pending review" --remove-label="in progress"'
alias gh-qa='gh pr edit --add-label="pending qa" --remove-label="pending review"'
